alter session set container = XEPDB1;

-- Special characters such as the ampersand will result in prompt without this directive.
SET DEFINE OFF;

insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'Injector', 'Accelerator division center for injectors and sources group', 'cis', 0, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'Mechanical Support', 'Accelerator division electrical engineering support services group', 'eess', 1, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'RF', 'Radio frequency electrical work group', 'rf', 2, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'SRF', 'Super radio frequency work group', 'srf', 3, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'Vacuum', 'Vacuum group', 'vac', 4, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'DC Power', 'DC Power group', 'dcpower', 5, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'Instrumentation & Controls', 'I&C group', 'ic', 6, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'Safety Systems', 'Safety group', 'ssg', 7, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'Survey & Alignment', 'Alignment group', 'alignment', 8, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'Accelerator Computing', 'Accelerator division computing group', 'acg', 9, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'Cyrogenics', 'Cryo group', 'cryo', 10, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'F&O', 'Facilities group', 'facilities', 11, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'ES&H', 'ES&H group', 'health', 12, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'Hall A (Moller Install)', 'Physics division Hall A', 'halla', 13, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'Hall B', 'I&C group', 'ic', 14, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'Hall C', 'I&C group', 'ic', 15, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'Hall D', 'I&C group', 'ic', 16, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'LERF', 'LERF group', 'ic', 17, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'Gun Test Stand', 'GTS group', 'ic', 18, 'N');
insert into PRESENTER_OWNER.TEAM (TEAM_ID, NAME, DESCRIPTION, DIRECTORY_GROUP_NAME, WEIGHT, ARCHIVED_YN) values (PRESENTER_OWNER.TEAM_ID.nextval, 'UITF', 'UITF group', 'ic', 19, 'N');

insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 1, TRUNC(SYSDATE), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 2, TRUNC(SYSDATE), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 3, TRUNC(SYSDATE), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 4, TRUNC(SYSDATE), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 5, TRUNC(SYSDATE), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 6, TRUNC(SYSDATE), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 1, TRUNC(SYSDATE - INTERVAL '1' DAY), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 2, TRUNC(SYSDATE - INTERVAL '1' DAY), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 3, TRUNC(SYSDATE - INTERVAL '1' DAY), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 4, TRUNC(SYSDATE - INTERVAL '1' DAY), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 5, TRUNC(SYSDATE - INTERVAL '1' DAY), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 6, TRUNC(SYSDATE - INTERVAL '1' DAY), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 1, TRUNC(SYSDATE - INTERVAL '2' DAY), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 2, TRUNC(SYSDATE - INTERVAL '2' DAY), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 3, TRUNC(SYSDATE - INTERVAL '2' DAY), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 4, TRUNC(SYSDATE - INTERVAL '2' DAY), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 5, TRUNC(SYSDATE - INTERVAL '2' DAY), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');
insert into PRESENTER_OWNER.TEAM_STATUS_REPORT(TEAM_STATUS_REPORT_ID, TEAM_ID, YMD, ACCOMPLISHED, IN_PROGRESS, PLANNED, ROADBLOCKS) values (PRESENTER_OWNER.TEAM_STATUS_REPORT_ID.nextval, 6, TRUNC(SYSDATE - INTERVAL '2' DAY), 'Nothing Accomplished!', 'Nothing in progress!', 'Nothing planned', 'Nothing blocking!');


