services:
  oracle:
    extends:
      file: compose.yaml
      service: oracle

  keycloak:
    extends:
      file: compose.yaml
      service: keycloak

  puppet:
    extends:
      file: compose.yaml
      service: puppet

  resize:
    extends:
      file: compose.yaml
      service: resize

  presenter:
    extends:
      file: compose.yaml
      service: presenter
    build:
      context: .
      dockerfile: Dockerfile