services:
  oracle:
    extends:
      file: deps.yaml
      service: oracle

  keycloak:
    extends:
      file: deps.yaml
      service: keycloak

  puppet:
    extends:
      file: deps.yaml
      service: puppet

  resize:
    extends:
      file: deps.yaml
      service: resize

  presenter:
    hostname: presenter
    container_name: presenter
    ports:
      - "8443:8443"
      - "8080:8080"
      - "9990:9990"
